### ISSUE TITLE
Separate Android Test module cannot be run

### ISSUE THREAD

**Issue by jupiter2359media** [googlesamples/android-testing-templates#13]
Hi,

Thank you for your work but I'm having an error trying to run tests inside a separate module.

Running tests inside `module-flavor1-androidTest-only` module only produces Empty test suite error by both Android Studio and gradle command `./gradlew module-flavor1-androidTest-only:connectedAndroidTest`

Another note, if I run a normal instrument test (which is located inside `app` module) first then the above tests can run without problem. My suspect is that the gradle command above doesn't install the app apk before execute the tests.

Can you guys check it out.

Thanks.

**Comment by JoseAlcerreca** [comment]
This was a problem months ago with build tools where cAT would not depend on assembleDebug so it was ignoring the tests. The workaround was

 ./gradlew module-flavor1-androidTest-only:assembleDebug module-flavor1-androidTest-only:connectedCheck

I'll check if this fix was reverted and report back. Thanks!

**Comment by slinzner** [comment]
Please re-open if you think this is still an issue

**Comment by Nainshri** [comment]
Not able to run separate test module. Getting error -
Test running failed: Unable to find instrumentation target package: com.example.android.testing.blueprint
Empty test suite.

**Comment by qmar** [comment]
Same problem here as @Nainshri. AS 1.5, doesn't work in IDE, works in command line gradle though.

**Comment by Nainshri** [comment]
Is it the case that the test-only module will only run if the application under test is already installed on the device?

**Comment by patrickhammond** [comment]
I’m continuing to see this with Android Studio 2.0 Beta and `com.android.tools.build:gradle:2.0.0-beta4` (just logged https://code.google.com/p/android/issues/detail?id=201081 against the tooling).

I’m using this as a workaround:
Go to Run/Debug Configurations, select the Android Tests configuration for the `module-flavor1-androidTest-only` module, click the add button in the “Before launch” section, pick “Gradle-aware Make”, set `installFlavor1Debug` in the Task field.  Hit OK.  Ensure that the `installFlavor1Debug` task is set first.  Screenshot of the Run/Debug config: https://cl.ly/1c1r2C3X1M3x

**Comment by venkata-kari** [comment]
AS 2.2 preview 4 and 2.1.2 stable versions invoking JUnit tests instead of AndroidTest configurations. I tried to Edit configurations and changing build.gradle files. No luck.
No changes were made to original project.
I get this following error. 
![screen shot 2016-06-15 at 12 35 45](https://cloud.githubusercontent.com/assets/1611815/16124320/66646794-33e6-11e6-8d86-c61cc009631a.png)

Tried to modify AS experimental feature (unification of both Instrumentation and JVM tests). No luck.

Please see G+ post https://plus.google.com/+GiridharKari/posts/LX3eDYf7deZ.
