### ISSUE TITLE
Error when build the project "No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha')."

### ISSUE THREAD

**Issue by umitems** [googlesamples/android-testing-templates#15]
No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha').

android-testing-templates-master\AndroidTestingBlueprint\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_textfield_search_material.xml

Error:Execution failed for task ':app:processFlavor1DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by Prashantbhagat** [comment]
stuck in same problem. please help me out.

**Comment by ashishbhandari** [comment]
I was getting the same problem, So I resolved the same by updating the sdk manager, select Android SDK Build-tools (23.0.1) and Android SDK Platforms-tool  (23.0.1) installed and update all of them.

**Comment by JoseAlcerreca** [comment]
Please re-open if still an issue.
