### ISSUE TITLE
Code coverage report is always 0%

### ISSUE THREAD

**Issue by vRallev** [googlesamples/android-testing-templates#18]
My project has a similar setup like the testing blueprint with an extra module for our Android tests. The app module has multiple flavors and build types (although I think that doesn't matter). If I try to create a code coverage report, then the coverage is 0% everywhere.

The Gradle plugin is trying to find and run the Android tests in the app module, but there are no tests. They are in the separate module. 

Let me know if you need more information.

(Repost from the bug tracker https://code.google.com/p/android/issues/detail?id=199555)

**Comment by JoseAlcerreca** [comment]
Sorry vRallev, it's really hard to understand what the problem is. It doesn't look like a problem with the sample.

If you want to report a bug the best way to reproduce is creating a PR against the testing template with the extra module, specifying what you executed and what you expected. It's not clear if you used AS or command line, for example.

I'm going to label this as not a samples issue for now.

**Comment by vRallev** [comment]
The label is correct, it's an issue in the Android Gradle plugin. I created a copy here, because the bug tracker changed to status to "Wrong Forum". I'm not sure what else I should do.

To clarify: I expect that the code coverage report finds the test code in a separate module. Right now it doesn't and the report has 0% coverage (although some of the code is tested, but in separate module). I create the coverage report from the command line.

**Comment by JoseAlcerreca** [comment]
We do have a androidTest-only module in the sample. Does that one work? What command are you executing?

**Comment by vRallev** [comment]
The following creates a coverage report with 89% coverage.
`./gradlew app:createFlavor1DebugCoverageReport`

Now add this class in the `:app` module.

```java
package com.example.android.testing.blueprint;

import android.content.Context;
import android.widget.Toast;

public class MyClass {
 
    public void test(Context context) {
        Toast.makeText(context, "Hello", Toast.LENGTH_SHORT).show();
    }
}
```

Recreate the coverage report results in a 75% coverage. Add the following method in the `AndroidTestOnlyModuleTest` class in the `module-flavor1-androidTest-only` module.

```java
    @Test
    public void testMyClass() throws InterruptedException {
        final CountDownLatch latch = new CountDownLatch(1);
        new Handler(Looper.getMainLooper()).post(new Runnable() {
            @Override
            public void run() {
                new MyClass().test(mContext);
                latch.countDown();
            }
        });

        latch.await();
    }
```

Although the code path tested, the coverage percent don't change. However, if I add the test method in the `:app` module, then the coverage report updates. 

The issue / question is: How can I create a test coverage report, which also checks the test code in a separate test module?

**Comment by JoseAlcerreca** [comment]
Yep that looks like a bug, if the test is executed it should be included in the report, I'll talk with the tools team. Thanks Ralf!

**Comment by vRallev** [comment]
Thanks @JoseAlcerreca I appreciate your help.

**Comment by slinzner** [comment]
@JoseAlcerreca any update on this?

**Comment by JoseAlcerreca** [comment]
Already in the correct tracker.
