### ISSUE TITLE
run EspressoTestForFlavor2 says No Tests were found

### ISSUE THREAD

**Issue by criswonder** [googlesamples/android-testing-templates#19]
Process finished with exit code 1
Class not found: "com.example.android.testing.blueprint.ui.espresso.EspressoTestForFlavor2"Empty test suite.

**Comment by amatkivskiy** [comment]
Couple of weeks reported this bug. https://code.google.com/p/android/issues/detail?id=202686

**Comment by slinzner** [comment]
Is this still an issue in Android Studio 2.2? Also please make sure you do run your tests as instrumentation tests and not as jvm tests. Android Studio sometimes gets confused about the type of test to run and accidentally show the context menu for local jvm tests.

**Comment by JoseAlcerreca** [comment]
It works for me.

 - From command line, `connectedFlavor2DebugAndroidTest` works.
 - From Android Studio, you need to specify the variant you want to use in the Build Variants window.

I just updated all the versions, so try again in any case.
