### ISSUE TITLE
How to import project? 

### ISSUE THREAD

**Issue by kamilwlf** [googlesamples/android-testing-templates#21]
My steps:
File -> New -> Project from version control -> github

Git URL:
https://github.com/googlesamples/android-testing-templates.git
then I see this:
![screenshot - 2016-08-24 11_26_39](https://cloud.githubusercontent.com/assets/7765963/17925547/aa345816-69ed-11e6-857a-d1343867d896.jpg)

I clicked "Configure"
and see this:
![2](https://cloud.githubusercontent.com/assets/7765963/17925594/cf0c2808-69ed-11e6-80a3-9bd3b2dec2ba.jpg)
I clicked "ok
and it does not work:
![3](https://cloud.githubusercontent.com/assets/7765963/17925643/059de14a-69ee-11e6-93ad-bd5debe14380.jpg)
"

**Comment by JoseAlcerreca** [comment]
Probably because the project is inside a directory. Just use git clone.

$ git clone https://github.com/googlesamples/android-testing-templates
