### ISSUE TITLE
Template should include an usage of a dependency from a custom maven repository

### ISSUE THREAD

**Issue by andrzejtokarski** [googlesamples/android-testing-templates#5]
Adding such dependency in the app module causes an "Failed to resolve" error.

```
repositories {
    maven { url "https://jitpack.io" }
    mavenCentral()
}

dependencies {
    // App's dependencies, including test
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.github.PhilJay:MPAndroidChart:v2.0.9'

...
```

If the same repositories are declared in the module-flavor1-androidTest-only module the dependencies resolve correctly.

**Comment by JoseAlcerreca** [comment]
Like discussed in #6, this would be a bug in the tools, not the samples, but this sample could be used to report it.
