### ISSUE TITLE
Template should include the Play Services dependency

### ISSUE THREAD

**Issue by andrzejtokarski** [googlesamples/android-testing-templates#6]
I'm mentioning this because adding Play Services dependency to the app module causes an error.

```
dependencies {
    // App's dependencies, including test
    compile('com.google.android.gms:play-services-base:7.5.0')
...
```

Reported error:
```
:module-flavor1-androidTest-only:processDebugManifest
/somewhere/android-testing-templates/AndroidTestingBlueprint/module-flavor1-androidTest-only/build/intermediates/manifests/full/debug/AndroidManifest.xml:29:28-65 : No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').
```

If there is a better place to report this issue please direct me to it.

**Comment by JoseAlcerreca** [comment]
It would be a bug in the build tools so please file it in b.android.com

Ideally, you can fork this project, add the lines that make it fail and add it to the bug report. That would make understanding the bug much easier. Thanks!

**Comment by andrzej-tokarski** [comment]
Submited the issue with the fork: https://code.google.com/p/android/issues/detail?id=182814&thanks=182814&ts=1439538894

**Comment by slinzner** [comment]
Thanks! We will follow up on android bugtracker
