### ISSUE TITLE
No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

### ISSUE THREAD

**Issue by tidezyc** [googlesamples/android-testing-templates#8]
I create a separate test module like `module-flavor1-androidTest-only`, and I get a error blew
```
Error:(36, 28) No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').
```

how can I fix this

**Comment by JoseAlcerreca** [comment]
Closing because it's not samples-related, but check this out
https://code.google.com/p/android/issues/detail?id=182814&thanks=182814&ts=1439538894
